kind: Secret
apiVersion: v1
metadata:
  name: pgadmin-secret
  namespace: database
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AZXhhbXBsZS5jb20= # admin@example.com
  PGADMIN_DEFAULT_PASSWORD: cGFzcw== # pass
