kind: Deployment
apiVersion: apps/v1
metadata:
  name: vaultwarden-deployment
  namespace: security
  labels:
    app: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: vaultwarden-data
              mountPath: /data/
      volumes:
        - name: vaultwarden-data
          persistentVolumeClaim:
            claimName: vaultwarden-data-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: vaultwarden
  namespace: security
spec:
  selector:
    app: vaultwarden
  ports:
    - name: http
      targetPort: http
      protocol: TCP
      port: 80
