kind: Secret
apiVersion: v1
metadata:
  name: homepage
  namespace: management
  labels:
    app.kubernetes.io/name: homepage
  annotations:
    kubernetes.io/service-account.name: homepage
type: kubernetes.io/service-account-token
