kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: proxy-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: [services, endpoints, secrets]
    verbs: [get, list, watch]
  - apiGroups: [extensions, networking.k8s.io]
    resources: [ingresses, ingressclasses]
    verbs: [get, list, watch]
  - apiGroups: [extensions, networking.k8s.io]
    resources: [ingresses/status]
    verbs: [update]
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: proxy-account
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: proxy-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: proxy-role
subjects:
  - kind: ServiceAccount
    name: proxy-account
    namespace: default
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: proxy-deployment
  namespace: default
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      serviceAccountName: proxy-account
      containers:
        - name: traefik
          image: traefik:v3.0
          ports:
            - name: http
              containerPort: 80
            - name: dashboard
              containerPort: 8080
          args:
            - --api.insecure
            - --providers.kubernetesingress
---
kind: Service
apiVersion: v1
metadata:
  name: proxy
  namespace: default
spec:
  selector:
    app: proxy
  ports:
    - name: http
      targetPort: http
      protocol: TCP
      port: 80
  type: LoadBalancer
